export interface DailyAyet {
  surahName: string;
  reference: string;
  arabic: string;
  turkish: string;
}

export const DAILY_AYETLER: DailyAyet[] = [
  { surahName: "Bakara", reference: "Bakara, 286", arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا", turkish: "Allah, hiçbir kimseye gücünün yeteceğinden başkasını yüklemez." },
  { surahName: "İnşirah", reference: "İnşirah, 5-6", arabic: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا", turkish: "Şüphesiz her zorlukla beraber bir kolaylık vardır." },
  { surahName: "Bakara", reference: "Bakara, 153", arabic: "إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ", turkish: "Şüphesiz Allah sabredenlerle beraberdir." },
  { surahName: "Talak", reference: "Talak, 3", arabic: "وَمَن يَتَوَكَّلْ عَلَى ٱللَّهِ فَهُوَ حَسْبُهُۥ", turkish: "Kim Allah'a tevekkül ederse, O kendisine yeter." },
  { surahName: "Ra'd", reference: "Ra'd, 28", arabic: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", turkish: "Bilesiniz ki, kalpler ancak Allah'ı anmakla huzur bulur." },
  { surahName: "Fatiha", reference: "Fatiha, 5", arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", turkish: "Yalnız sana ibadet eder ve yalnız senden yardım dileriz." },
  { surahName: "Mü'min", reference: "Mü'min, 60", arabic: "ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ", turkish: "Bana dua edin, kabul edeyim." },
  { surahName: "Bakara", reference: "Bakara, 152", arabic: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ", turkish: "Öyle ise siz beni anın ki, ben de sizi anayım." },
  { surahName: "İhlas", reference: "İhlas, 1-2", arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ", turkish: "De ki: O Allah birdir. Allah Samed'dir." },
  { surahName: "Zümer", reference: "Zümer, 53", arabic: "لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ", turkish: "Allah'ın rahmetinden ümit kesmeyin." },
  { surahName: "Bakara", reference: "Bakara, 45", arabic: "وَٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ", turkish: "Sabır ve namazla Allah'tan yardım isteyin." },
  { surahName: "Nisâ", reference: "Nisâ, 110", arabic: "وَمَن يَعْمَلْ سُوٓءًا أَوْ يَظْلِمْ نَفْسَهُۥ ثُمَّ يَسْتَغْفِرِ ٱللَّهَ يَجِدِ ٱللَّهَ غَفُورًا رَّحِيمًا", turkish: "Kim bir kötülük yapar veya nefsine zulmeder de sonra Allah'tan bağışlanma dilerse Allah'ı bağışlayıcı ve esirgeyici bulur." },
  { surahName: "Âl-i İmrân", reference: "Âl-i İmrân, 139", arabic: "وَلَا تَهِنُوا۟ وَلَا تَحْزَنُوا۟ وَأَنتُمُ ٱلْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ", turkish: "Gevşemeyin, üzülmeyin; eğer iman etmişseniz, üstün olan sizsiniz." },
  { surahName: "Tevbe", reference: "Tevbe, 51", arabic: "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا", turkish: "De ki: Bize Allah'ın yazdığından başkası asla isabet etmez." },
  { surahName: "Yûnus", reference: "Yûnus, 62", arabic: "أَلَآ إِنَّ أَوْلِيَآءَ ٱللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", turkish: "Bilesiniz ki, Allah'ın dostları için ne korku vardır, ne de onlar üzüleceklerdir." },
  { surahName: "Hûd", reference: "Hûd, 88", arabic: "وَمَا تَوْفِيقِىٓ إِلَّا بِٱللَّهِ ۚ عَلَيْهِ تَوَكَّلْتُ وَإِلَيْهِ أُنِيبُ", turkish: "Başarım ancak Allah'tandır. Yalnız O'na dayandım ve yalnız O'na yöneliyorum." },
  { surahName: "Yûsuf", reference: "Yûsuf, 87", arabic: "إِنَّهُۥ لَا يَا۟يْـَٔسُ مِن رَّوْحِ ٱللَّهِ إِلَّا ٱلْقَوْمُ ٱلْكَـٰفِرُونَ", turkish: "Allah'ın rahmetinden ancak inkâr eden kavim ümit keser." },
  { surahName: "İbrâhim", reference: "İbrâhim, 7", arabic: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", turkish: "Eğer şükrederseniz, elbette size nimetimi artırırım." },
  { surahName: "Nahl", reference: "Nahl, 53", arabic: "وَمَا بِكُم مِّن نِّعْمَةٍ فَمِنَ ٱللَّهِ", turkish: "Size ulaşan her nimet Allah'tandır." },
  { surahName: "Nahl", reference: "Nahl, 96", arabic: "مَا عِندَكُمْ يَنفَدُ ۖ وَمَا عِندَ ٱللَّهِ بَاقٍ", turkish: "Sizin yanınızdaki tükenir, Allah'ın yanındaki ise kalıcıdır." },
  { surahName: "İsrâ", reference: "İsrâ, 80", arabic: "وَقُل رَّبِّ أَدْخِلْنِى مُدْخَلَ صِدْقٍ وَأَخْرِجْنِى مُخْرَجَ صِدْقٍ", turkish: "De ki: Rabbim! Beni doğru bir girişle girdir ve doğru bir çıkışla çıkar." },
  { surahName: "Kehf", reference: "Kehf, 23-24", arabic: "وَلَا تَقُولَنَّ لِشَا۟ىْءٍ إِنِّى فَاعِلٌ ذَٰلِكَ غَدًا ۝ إِلَّآ أَن يَشَآءَ ٱللَّهُ", turkish: "Hiçbir şey için 'Ben bunu yarın yapacağım' deme. Ancak 'İnşaallah' de." },
  { surahName: "Meryem", reference: "Meryem, 96", arabic: "إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ سَيَجْعَلُ لَهُمُ ٱلرَّحْمَٰنُ وُدًّا", turkish: "İman edip iyi işler yapanlar için Rahman bir sevgi yaratacaktır." },
  { surahName: "Tâ-Hâ", reference: "Tâ-Hâ, 25-28", arabic: "رَبِّ ٱشْرَحْ لِى صَدْرِى وَيَسِّرْ لِىٓ أَمْرِى", turkish: "Rabbim! Göğsüme genişlik ver, işimi kolaylaştır." },
  { surahName: "Enbiyâ", reference: "Enbiyâ, 87", arabic: "لَّآ إِلَٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّـٰلِمِينَ", turkish: "Senden başka ilah yoktur. Sen yücesin. Şüphesiz ben kendine zulmedenlerden oldum." },
  { surahName: "Mü'minûn", reference: "Mü'minûn, 118", arabic: "رَّبِّ ٱغْفِرْ وَٱرْحَمْ وَأَنتَ خَيْرُ ٱلرَّٰحِمِينَ", turkish: "Rabbim! Bağışla, merhamet et. Sen merhamet edenlerin en hayırlısısın." },
  { surahName: "Furkân", reference: "Furkân, 74", arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَٰجِنَا وَذُرِّيَّـٰتِنَا قُرَّةَ أَعْيُنٍ", turkish: "Rabbimiz! Bize eşlerimizden ve soyumuzdan göz aydınlığı bağışla." },
  { surahName: "Kasas", reference: "Kasas, 24", arabic: "رَبِّ إِنِّى لِمَآ أَنزَلْتَ إِلَىَّ مِنْ خَيْرٍ فَقِيرٌ", turkish: "Rabbim! Bana indireceğin her hayra muhtacım." },
  { surahName: "Ankebût", reference: "Ankebût, 69", arabic: "وَٱلَّذِينَ جَـٰهَدُوا۟ فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", turkish: "Bizim uğrumuzda cihad edenleri elbette yollarımıza ileteceğiz." },
  { surahName: "Rûm", reference: "Rûm, 21", arabic: "وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً", turkish: "Aranızda sevgi ve merhamet var etti." },
  { surahName: "Lokmân", reference: "Lokmân, 17", arabic: "وَٱصْبِرْ عَلَىٰ مَآ أَصَابَكَ ۖ إِنَّ ذَٰلِكَ مِنْ عَزْمِ ٱلْأُمُورِ", turkish: "Başına gelene sabret. Şüphesiz bu, azim isteyen işlerdendir." },
  { surahName: "Ahzâb", reference: "Ahzâb, 41", arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱذْكُرُوا۟ ٱللَّهَ ذِكْرًا كَثِيرًا", turkish: "Ey iman edenler! Allah'ı çokça anın." },
  { surahName: "Fâtır", reference: "Fâtır, 5", arabic: "إِنَّ وَعْدَ ٱللَّهِ حَقٌّ", turkish: "Şüphesiz Allah'ın vaadi gerçektir." },
  { surahName: "Yâsîn", reference: "Yâsîn, 82", arabic: "إِنَّمَآ أَمْرُهُۥٓ إِذَآ أَرَادَ شَيْـًٔا أَن يَقُولَ لَهُۥ كُن فَيَكُونُ", turkish: "Bir şeyi dilediğinde, O'nun emri sadece 'Ol!' demesidir; o da hemen oluverir." },
  { surahName: "Sâffât", reference: "Sâffât, 173", arabic: "وَإِنَّ جُندَنَا لَهُمُ ٱلْغَـٰلِبُونَ", turkish: "Şüphesiz bizim ordumuz galip gelecektir." },
  { surahName: "Zümer", reference: "Zümer, 10", arabic: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", turkish: "Sabredenlere mükafatları hesapsız ödenecektir." },
  { surahName: "Mü'min", reference: "Mü'min, 44", arabic: "وَأُفَوِّضُ أَمْرِىٓ إِلَى ٱللَّهِ", turkish: "Ben işimi Allah'a havale ediyorum." },
  { surahName: "Şûrâ", reference: "Şûrâ, 19", arabic: "ٱللَّهُ لَطِيفٌۢ بِعِبَادِهِۦ", turkish: "Allah, kullarına lütufkârdır." },
  { surahName: "Zuhruf", reference: "Zuhruf, 32", arabic: "وَرَحْمَتُ رَبِّكَ خَيْرٌ مِّمَّا يَجْمَعُونَ", turkish: "Rabbinin rahmeti, onların biriktirdiklerinden daha hayırlıdır." },
  { surahName: "Câsiye", reference: "Câsiye, 13", arabic: "وَسَخَّرَ لَكُم مَّا فِى ٱلسَّمَـٰوَٰتِ وَمَا فِى ٱلْأَرْضِ جَمِيعًا مِّنْهُ", turkish: "Göklerde ve yerde olanların hepsini, kendinden bir nimet olarak size hizmetinize verdi." },
  { surahName: "Muhammed", reference: "Muhammed, 7", arabic: "إِن تَنصُرُوا۟ ٱللَّهَ يَنصُرْكُمْ وَيُثَبِّتْ أَقْدَامَكُمْ", turkish: "Eğer Allah'a yardım ederseniz, O da size yardım eder ve ayaklarınızı sabit kılar." },
  { surahName: "Fetih", reference: "Fetih, 4", arabic: "هُوَ ٱلَّذِىٓ أَنزَلَ ٱلسَّكِينَةَ فِى قُلُوبِ ٱلْمُؤْمِنِينَ", turkish: "Mü'minlerin kalplerine huzur indiren O'dur." },
  { surahName: "Hucurât", reference: "Hucurât, 13", arabic: "إِنَّ أَكْرَمَكُمْ عِندَ ٱللَّهِ أَتْقَىٰكُمْ", turkish: "Allah katında en üstününüz, O'na karşı en saygılı olanınızdır." },
  { surahName: "Kâf", reference: "Kâf, 16", arabic: "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ ٱلْوَرِيدِ", turkish: "Biz ona şah damarından daha yakınız." },
  { surahName: "Zâriyât", reference: "Zâriyât, 56", arabic: "وَمَا خَلَقْتُ ٱلْجِنَّ وَٱلْإِنسَ إِلَّا لِيَعْبُدُونِ", turkish: "Ben cinleri ve insanları, ancak bana ibadet etsinler diye yarattım." },
  { surahName: "Necm", reference: "Necm, 39", arabic: "وَأَن لَّيْسَ لِلْإِنسَـٰنِ إِلَّا مَا سَعَىٰ", turkish: "İnsan için ancak çalıştığının karşılığı vardır." },
  { surahName: "Rahmân", reference: "Rahmân, 13", arabic: "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ", turkish: "O halde Rabbinizin nimetlerinden hangisini yalanlayabilirsiniz?" },
  { surahName: "Vâkıa", reference: "Vâkıa, 79", arabic: "لَّا يَمَسُّهُۥٓ إِلَّا ٱلْمُطَهَّرُونَ", turkish: "Ona ancak temizlenmiş olanlar dokunabilir." },
  { surahName: "Hadîd", reference: "Hadîd, 4", arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", turkish: "Nerede olsanız, O sizinle beraberdir." },
  { surahName: "Mücâdele", reference: "Mücâdele, 11", arabic: "يَرْفَعِ ٱللَّهُ ٱلَّذِينَ ءَامَنُوا۟ مِنكُمْ وَٱلَّذِينَ أُوتُوا۟ ٱلْعِلْمَ دَرَجَـٰتٍ", turkish: "Allah, içinizden iman edenleri ve kendilerine ilim verilenleri derecelerle yüceltir." },
  { surahName: "Haşr", reference: "Haşr, 18", arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱتَّقُوا۟ ٱللَّهَ وَلْتَنظُرْ نَفْسٌ مَّا قَدَّمَتْ لِغَدٍ", turkish: "Ey iman edenler! Allah'tan korkun ve herkes yarın için ne hazırladığına baksın." },
  { surahName: "Talâk", reference: "Talâk, 2-3", arabic: "وَمَن يَتَّقِ ٱللَّهَ يَجْعَل لَّهُۥ مَخْرَجًا ۝ وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ", turkish: "Kim Allah'tan korkarsa Allah ona bir çıkış yolu sağlar ve onu beklemediği yerden rızıklandırır." },
  { surahName: "Tahrîm", reference: "Tahrîm, 8", arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ تُوبُوٓا۟ إِلَى ٱللَّهِ تَوْبَةً نَّصُوحًا", turkish: "Ey iman edenler! Allah'a gönülden bir tövbe ile tövbe edin." },
  { surahName: "Mülk", reference: "Mülk, 1", arabic: "تَبَارَكَ ٱلَّذِى بِيَدِهِ ٱلْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ", turkish: "Mülk elinde olan Allah, çok yücedir. O her şeye gücü yetendir." },
  { surahName: "Kalem", reference: "Kalem, 4", arabic: "وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ", turkish: "Şüphesiz sen yüce bir ahlak üzeresin." },
  { surahName: "Müzzemmil", reference: "Müzzemmil, 8", arabic: "وَٱذْكُرِ ٱسْمَ رَبِّكَ وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا", turkish: "Rabbinin adını an ve bütün varlığınla O'na yönel." },
  { surahName: "Müddessir", reference: "Müddessir, 7", arabic: "وَلِرَبِّكَ فَٱصْبِرْ", turkish: "Rabbin için sabret." },
  { surahName: "İnsân", reference: "İnsân, 3", arabic: "إِنَّا هَدَيْنَـٰهُ ٱلسَّبِيلَ إِمَّا شَاكِرًا وَإِمَّآ كَفُورًا", turkish: "Şüphesiz biz ona yolu gösterdik; ister şükreder, ister nankörlük eder." },
  { surahName: "Nebe'", reference: "Nebe', 9", arabic: "وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا", turkish: "Uykunuzu bir dinlenme kıldık." },
  { surahName: "Abese", reference: "Abese, 24", arabic: "فَلْيَنظُرِ ٱلْإِنسَـٰنُ إِلَىٰ طَعَامِهِۦٓ", turkish: "İnsan, yediği şeylere baksın." },
  { surahName: "İnşikâk", reference: "İnşikâk, 6", arabic: "يَـٰٓأَيُّهَا ٱلْإِنسَـٰنُ إِنَّكَ كَادِحٌ إِلَىٰ رَبِّكَ كَدْحًا فَمُلَـٰقِيهِ", turkish: "Ey insan! Sen Rabbine kavuşuncaya kadar didinip duracaksın, sonunda O'na kavuşacaksın." },
  { surahName: "A'lâ", reference: "A'lâ, 14-15", arabic: "قَدْ أَفْلَحَ مَن تَزَكَّىٰ ۝ وَذَكَرَ ٱسْمَ رَبِّهِۦ فَصَلَّىٰ", turkish: "Arınıp temizlenen ve Rabbinin adını anıp namaz kılan kurtulmuştur." },
  { surahName: "Fecr", reference: "Fecr, 27-30", arabic: "يَـٰٓأَيَّتُهَا ٱلنَّفْسُ ٱلْمُطْمَئِنَّةُ ۝ ٱرْجِعِىٓ إِلَىٰ رَبِّكِ رَاضِيَةً مَّرْضِيَّةً", turkish: "Ey huzura ermiş nefis! Razı olmuş ve razı olunmuş olarak Rabbine dön." },
  { surahName: "Şems", reference: "Şems, 9-10", arabic: "قَدْ أَفْلَحَ مَن زَكَّىٰهَا ۝ وَقَدْ خَابَ مَن دَسَّىٰهَا", turkish: "Nefsini arındıran kurtulmuştur. Onu kötülüklere gömen ise ziyana uğramıştır." },
  { surahName: "Leyl", reference: "Leyl, 5-7", arabic: "فَأَمَّا مَنْ أَعْطَىٰ وَٱتَّقَىٰ ۝ وَصَدَّقَ بِٱلْحُسْنَىٰ ۝ فَسَنُيَسِّرُهُۥ لِلْيُسْرَىٰ", turkish: "Kim verir ve sakınırsa, en güzeli tasdik ederse, biz de onu en kolay olana hazırlarız." },
  { surahName: "Duhâ", reference: "Duhâ, 4", arabic: "وَلَلْـَٔاخِرَةُ خَيْرٌ لَّكَ مِنَ ٱلْأُولَىٰ", turkish: "Şüphesiz ahiret senin için dünyadan daha hayırlıdır." },
  { surahName: "Duhâ", reference: "Duhâ, 11", arabic: "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ", turkish: "Rabbinin nimetini ise anlat." },
  { surahName: "İnşirah", reference: "İnşirah, 7-8", arabic: "فَإِذَا فَرَغْتَ فَٱنصَبْ ۝ وَإِلَىٰ رَبِّكَ فَٱرْغَب", turkish: "Boş kaldığın zaman çalışmaya koyul, ancak Rabbine yönel." },
  { surahName: "Tîn", reference: "Tîn, 4", arabic: "لَقَدْ خَلَقْنَا ٱلْإِنسَـٰنَ فِىٓ أَحْسَنِ تَقْوِيمٍ", turkish: "Andolsun ki biz insanı en güzel biçimde yarattık." },
  { surahName: "Alâk", reference: "Alâk, 1", arabic: "ٱقْرَأْ بِٱسْمِ رَبِّكَ ٱلَّذِى خَلَقَ", turkish: "Yaratan Rabbinin adıyla oku." },
  { surahName: "Kadr", reference: "Kadr, 3", arabic: "لَيْلَةُ ٱلْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ", turkish: "Kadir gecesi bin aydan daha hayırlıdır." },
  { surahName: "Zilzâl", reference: "Zilzâl, 7-8", arabic: "فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُۥ ۝ وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُۥ", turkish: "Kim zerre miktarı hayır işlerse onu görür. Kim de zerre miktarı şer işlerse onu görür." },
  { surahName: "Asr", reference: "Asr, 1-3", arabic: "وَٱلْعَصْرِ ۝ إِنَّ ٱلْإِنسَـٰنَ لَفِى خُسْرٍ", turkish: "Asra yemin olsun ki, insan gerçekten ziyandadır." },
  { surahName: "Kevser", reference: "Kevser, 1-2", arabic: "إِنَّآ أَعْطَيْنَـٰكَ ٱلْكَوْثَرَ ۝ فَصَلِّ لِرَبِّكَ وَٱنْحَرْ", turkish: "Şüphesiz biz sana Kevser'i verdik. Öyleyse Rabbin için namaz kıl ve kurban kes." },
  { surahName: "İhlâs", reference: "İhlâs, 1-4", arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ", turkish: "De ki: O, Allah birdir. Allah Samed'dir." },
  { surahName: "Felâk", reference: "Felâk, 1", arabic: "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ", turkish: "De ki: Yarılan sabahın Rabbine sığınırım." },
  { surahName: "Nâs", reference: "Nâs, 1-3", arabic: "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ", turkish: "De ki: İnsanların Rabbine, hükümdarına, ilahına sığınırım." },
  { surahName: "Bakara", reference: "Bakara, 255", arabic: "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ", turkish: "Allah, kendisinden başka ilah olmayan, daima diri ve yarattıklarını koruyup yönetendir." },
  { surahName: "Bakara", reference: "Bakara, 186", arabic: "وَإِذَا سَأَلَكَ عِبَادِى عَنِّى فَإِنِّى قَرِيبٌ", turkish: "Kullarım sana benden sorduğunda; gerçekten ben onlara çok yakınım." },
  { surahName: "Bakara", reference: "Bakara, 216", arabic: "وَعَسَىٰٓ أَن تَكْرَهُوا۟ شَيْـًٔا وَهُوَ خَيْرٌ لَّكُمْ", turkish: "Hoşunuza gitmeyen bir şey, sizin için hayırlı olabilir." },
  { surahName: "Âl-i İmrân", reference: "Âl-i İmrân, 8", arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا", turkish: "Rabbimiz! Bizi hidayete erdirdikten sonra kalplerimizi kaydırma." },
  { surahName: "Âl-i İmrân", reference: "Âl-i İmrân, 26", arabic: "قُلِ ٱللَّهُمَّ مَـٰلِكَ ٱلْمُلْكِ تُؤْتِى ٱلْمُلْكَ مَن تَشَآءُ", turkish: "De ki: Mülkün gerçek sahibi Allah'ım, mülkü dilediğine verirsin." },
  { surahName: "Âl-i İmrân", reference: "Âl-i İmrân, 159", arabic: "فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى ٱللَّهِ", turkish: "Bir kez karar verince de artık Allah'a güven." },
  { surahName: "Âl-i İmrân", reference: "Âl-i İmrân, 200", arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱصْبِرُوا۟ وَصَابِرُوا۟ وَرَابِطُوا۟ وَٱتَّقُوا۟ ٱللَّهَ", turkish: "Ey iman edenler! Sabredin, sabır yarışında düşmanlarınızı geçin, hazır kıtalı olun ve Allah'tan korkun." },
  { surahName: "Nisâ", reference: "Nisâ, 86", arabic: "وَإِذَا حُيِّيتُم بِتَحِيَّةٍ فَحَيُّوا۟ بِأَحْسَنَ مِنْهَآ أَوْ رُدُّوهَآ", turkish: "Bir selam ile selamlandığınızda, ondan daha güzeliyle veya aynısı ile karşılık verin." },
  { surahName: "Mâide", reference: "Mâide, 32", arabic: "مَن قَتَلَ نَفْسًۢا بِغَيْرِ نَفْسٍ أَوْ فَسَادٍ فِى ٱلْأَرْضِ فَكَأَنَّمَا قَتَلَ ٱلنَّاسَ جَمِيعًا", turkish: "Kim bir cana kıymamış veya yeryüzünde fesat çıkarmamış birini öldürürse, sanki bütün insanları öldürmüş gibi olur." },
  { surahName: "En'âm", reference: "En'âm, 162", arabic: "قُلْ إِنَّ صَلَاتِى وَنُسُكِى وَمَحْيَاىَ وَمَمَاتِى لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ", turkish: "De ki: Şüphesiz benim namazım, ibadetlerim, hayatım ve ölümüm âlemlerin Rabbi olan Allah içindir." },
  { surahName: "A'râf", reference: "A'râf, 23", arabic: "رَبَّنَا ظَلَمْنَآ أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ ٱلْخَـٰسِرِينَ", turkish: "Rabbimiz! Biz nefsimize zulmettik. Eğer bizi bağışlamaz ve bize merhamet etmezsen kaybedenlerden oluruz." },
  { surahName: "A'râf", reference: "A'râf, 55", arabic: "ٱدْعُوا۟ رَبَّكُمْ تَضَرُّعًا وَخُفْيَةً", turkish: "Rabbinize yalvararak ve gizlice dua edin." },
  { surahName: "Yûnus", reference: "Yûnus, 26", arabic: "لِّلَّذِينَ أَحْسَنُوا۟ ٱلْحُسْنَىٰ وَزِيَادَةٌ", turkish: "İyilik yapanlara daha güzeli ve fazlası vardır." },
  { surahName: "Hûd", reference: "Hûd, 6", arabic: "وَمَا مِن دَآبَّةٍ فِى ٱلْأَرْضِ إِلَّا عَلَى ٱللَّهِ رِزْقُهَا", turkish: "Yeryüzünde hiçbir canlı yoktur ki, rızkı Allah'a ait olmasın." },
  { surahName: "Yûsuf", reference: "Yûsuf, 18", arabic: "فَصَبْرٌ جَمِيلٌ ۖ وَٱللَّهُ ٱلْمُسْتَعَانُ", turkish: "Artık güzelce sabretmek gerek. Yardımına başvurulacak olan da Allah'tır." },
  { surahName: "İsrâ", reference: "İsrâ, 23-24", arabic: "وَبِٱلْوَٰلِدَيْنِ إِحْسَـٰنًا", turkish: "Anaya ve babaya iyi davranın." },
  { surahName: "İsrâ", reference: "İsrâ, 32", arabic: "وَلَا تَقْرَبُوا۟ ٱلزِّنَىٰٓ ۖ إِنَّهُۥ كَانَ فَـٰحِشَةً", turkish: "Zinaya yaklaşmayın; şüphesiz o, bir hayasızlıktır." },
  { surahName: "Kehf", reference: "Kehf, 110", arabic: "فَمَن كَانَ يَرْجُوا۟ لِقَآءَ رَبِّهِۦ فَلْيَعْمَلْ عَمَلًا صَـٰلِحًا", turkish: "Kim Rabbine kavuşmayı umuyorsa, salih amel işlesin." },
  { surahName: "Tâ-Hâ", reference: "Tâ-Hâ, 114", arabic: "وَقُل رَّبِّ زِدْنِى عِلْمًا", turkish: "De ki: Rabbim, ilmimi artır." },
  { surahName: "Enbiyâ", reference: "Enbiyâ, 107", arabic: "وَمَآ أَرْسَلْنَـٰكَ إِلَّا رَحْمَةً لِّلْعَـٰلَمِينَ", turkish: "Biz seni ancak âlemlere rahmet olarak gönderdik." },
  { surahName: "Furkân", reference: "Furkân, 63", arabic: "وَعِبَادُ ٱلرَّحْمَـٰنِ ٱلَّذِينَ يَمْشُونَ عَلَى ٱلْأَرْضِ هَوْنًا", turkish: "Rahman'ın kulları yeryüzünde alçakgönüllüce yürüyenlerdir." },
  { surahName: "Lokmân", reference: "Lokmân, 18", arabic: "وَلَا تُصَعِّرْ خَدَّكَ لِلنَّاسِ وَلَا تَمْشِ فِى ٱلْأَرْضِ مَرَحًا", turkish: "Yüzünü insanlardan kibirle çevirme ve yeryüzünde böbürlenerek yürüme." },
  { surahName: "Yâsîn", reference: "Yâsîn, 12", arabic: "إِنَّا نَحْنُ نُحْىِ ٱلْمَوْتَىٰ وَنَكْتُبُ مَا قَدَّمُوا۟ وَءَاثَـٰرَهُمْ", turkish: "Şüphesiz biz ölüleri biziz dirilten. Onların yaptıklarını ve bıraktıklarını yazıyoruz." },
  { surahName: "Zümer", reference: "Zümer, 9", arabic: "هَلْ يَسْتَوِى ٱلَّذِينَ يَعْلَمُونَ وَٱلَّذِينَ لَا يَعْلَمُونَ", turkish: "Hiç bilenlerle bilmeyenler bir olur mu?" },
  { surahName: "Şûrâ", reference: "Şûrâ, 11", arabic: "لَيْسَ كَمِثْلِهِۦ شَىْءٌ ۖ وَهُوَ ٱلسَّمِيعُ ٱلْبَصِيرُ", turkish: "O'nun benzeri hiçbir şey yoktur. O, hakkıyla işitendir, hakkıyla görendir." },
  { surahName: "Hucurât", reference: "Hucurât, 10", arabic: "إِنَّمَا ٱلْمُؤْمِنُونَ إِخْوَةٌ", turkish: "Şüphesiz mü'minler birbirinin kardeşidir." },
  { surahName: "Hucurât", reference: "Hucurât, 12", arabic: "وَلَا يَغْتَب بَّعْضُكُم بَعْضًا", turkish: "Biriniz diğerini gıybet etmesin." },
  { surahName: "Tegâbün", reference: "Tegâbün, 11", arabic: "مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذْنِ ٱللَّهِ", turkish: "Allah'ın izni olmadıkça hiçbir musibet isabet etmez." },
  { surahName: "Mülk", reference: "Mülk, 2", arabic: "ٱلَّذِى خَلَقَ ٱلْمَوْتَ وَٱلْحَيَوٰةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا", turkish: "O, hanginizin daha güzel iş yapacağını sınamak için ölümü ve hayatı yaratandır." },
];

export function getDailyAyet(date: Date = new Date()): DailyAyet {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return DAILY_AYETLER[dayOfYear % DAILY_AYETLER.length]!;
}

export function getAyetForSlot(slot: number): DailyAyet {
  return DAILY_AYETLER[Math.abs(slot) % DAILY_AYETLER.length]!;
}
