export interface SurahMeta {
  no: number;
  turkish: string;
  arabic: string;
  english: string;
  meaning: string;
  ayetCount: number;
  type: "Mekki" | "Medeni";
}

export const SURELER_META: SurahMeta[] = [
  { no: 1, turkish: "Fâtiha", arabic: "ٱلْفَاتِحَة", english: "Al-Fatihah", meaning: "Açılış", ayetCount: 7, type: "Mekki" },
  { no: 2, turkish: "Bakara", arabic: "ٱلْبَقَرَة", english: "Al-Baqarah", meaning: "İnek", ayetCount: 286, type: "Medeni" },
  { no: 3, turkish: "Âl-i İmrân", arabic: "آلِ عِمْرَان", english: "Aali Imran", meaning: "İmran Ailesi", ayetCount: 200, type: "Medeni" },
  { no: 4, turkish: "Nisâ", arabic: "ٱلنِّسَاء", english: "An-Nisa", meaning: "Kadınlar", ayetCount: 176, type: "Medeni" },
  { no: 5, turkish: "Mâide", arabic: "ٱلْمَائِدَة", english: "Al-Ma'idah", meaning: "Sofra", ayetCount: 120, type: "Medeni" },
  { no: 6, turkish: "En'âm", arabic: "ٱلْأَنْعَام", english: "Al-An'am", meaning: "Davarlar", ayetCount: 165, type: "Mekki" },
  { no: 7, turkish: "A'râf", arabic: "ٱلْأَعْرَاف", english: "Al-A'raf", meaning: "Yüksek Yerler", ayetCount: 206, type: "Mekki" },
  { no: 8, turkish: "Enfâl", arabic: "ٱلْأَنْفَال", english: "Al-Anfal", meaning: "Ganimetler", ayetCount: 75, type: "Medeni" },
  { no: 9, turkish: "Tevbe", arabic: "ٱلتَّوْبَة", english: "At-Tawbah", meaning: "Tövbe", ayetCount: 129, type: "Medeni" },
  { no: 10, turkish: "Yûnus", arabic: "يُونُس", english: "Yunus", meaning: "Yunus", ayetCount: 109, type: "Mekki" },
  { no: 11, turkish: "Hûd", arabic: "هُود", english: "Hud", meaning: "Hud", ayetCount: 123, type: "Mekki" },
  { no: 12, turkish: "Yûsuf", arabic: "يُوسُف", english: "Yusuf", meaning: "Yusuf", ayetCount: 111, type: "Mekki" },
  { no: 13, turkish: "Ra'd", arabic: "ٱلرَّعْد", english: "Ar-Ra'd", meaning: "Gök Gürültüsü", ayetCount: 43, type: "Medeni" },
  { no: 14, turkish: "İbrâhim", arabic: "إِبْرَاهِيم", english: "Ibrahim", meaning: "İbrahim", ayetCount: 52, type: "Mekki" },
  { no: 15, turkish: "Hicr", arabic: "ٱلْحِجْر", english: "Al-Hijr", meaning: "Hicr", ayetCount: 99, type: "Mekki" },
  { no: 16, turkish: "Nahl", arabic: "ٱلنَّحْل", english: "An-Nahl", meaning: "Bal Arısı", ayetCount: 128, type: "Mekki" },
  { no: 17, turkish: "İsrâ", arabic: "ٱلْإِسْرَاء", english: "Al-Isra", meaning: "Gece Yürüyüşü", ayetCount: 111, type: "Mekki" },
  { no: 18, turkish: "Kehf", arabic: "ٱلْكَهْف", english: "Al-Kahf", meaning: "Mağara", ayetCount: 110, type: "Mekki" },
  { no: 19, turkish: "Meryem", arabic: "مَرْيَم", english: "Maryam", meaning: "Meryem", ayetCount: 98, type: "Mekki" },
  { no: 20, turkish: "Tâ-Hâ", arabic: "طٰهٰ", english: "Taha", meaning: "Tâ-Hâ", ayetCount: 135, type: "Mekki" },
  { no: 21, turkish: "Enbiyâ", arabic: "ٱلْأَنْبِيَاء", english: "Al-Anbya", meaning: "Peygamberler", ayetCount: 112, type: "Mekki" },
  { no: 22, turkish: "Hac", arabic: "ٱلْحَجّ", english: "Al-Hajj", meaning: "Hac", ayetCount: 78, type: "Medeni" },
  { no: 23, turkish: "Mü'minûn", arabic: "ٱلْمُؤْمِنُون", english: "Al-Mu'minun", meaning: "Mü'minler", ayetCount: 118, type: "Mekki" },
  { no: 24, turkish: "Nûr", arabic: "ٱلنُّور", english: "An-Nur", meaning: "Nur", ayetCount: 64, type: "Medeni" },
  { no: 25, turkish: "Furkân", arabic: "ٱلْفُرْقَان", english: "Al-Furqan", meaning: "Ayırt Eden", ayetCount: 77, type: "Mekki" },
  { no: 26, turkish: "Şuarâ", arabic: "ٱلشُّعَرَاء", english: "Ash-Shu'ara", meaning: "Şairler", ayetCount: 227, type: "Mekki" },
  { no: 27, turkish: "Neml", arabic: "ٱلنَّمْل", english: "An-Naml", meaning: "Karınca", ayetCount: 93, type: "Mekki" },
  { no: 28, turkish: "Kasas", arabic: "ٱلْقَصَص", english: "Al-Qasas", meaning: "Kıssalar", ayetCount: 88, type: "Mekki" },
  { no: 29, turkish: "Ankebût", arabic: "ٱلْعَنْكَبُوت", english: "Al-Ankabut", meaning: "Örümcek", ayetCount: 69, type: "Mekki" },
  { no: 30, turkish: "Rûm", arabic: "ٱلرُّوم", english: "Ar-Rum", meaning: "Romalılar", ayetCount: 60, type: "Mekki" },
  { no: 31, turkish: "Lokmân", arabic: "لُقْمَان", english: "Luqman", meaning: "Lokman", ayetCount: 34, type: "Mekki" },
  { no: 32, turkish: "Secde", arabic: "ٱلسَّجْدَة", english: "As-Sajdah", meaning: "Secde", ayetCount: 30, type: "Mekki" },
  { no: 33, turkish: "Ahzâb", arabic: "ٱلْأَحْزَاب", english: "Al-Ahzab", meaning: "Birleşik Topluluklar", ayetCount: 73, type: "Medeni" },
  { no: 34, turkish: "Sebe'", arabic: "سَبَإ", english: "Saba", meaning: "Sebe", ayetCount: 54, type: "Mekki" },
  { no: 35, turkish: "Fâtır", arabic: "فَاطِر", english: "Fatir", meaning: "Yaratan", ayetCount: 45, type: "Mekki" },
  { no: 36, turkish: "Yâsîn", arabic: "يٰسٓ", english: "Ya-Sin", meaning: "Yâsîn", ayetCount: 83, type: "Mekki" },
  { no: 37, turkish: "Sâffât", arabic: "ٱلصَّافَّات", english: "As-Saffat", meaning: "Saf Tutanlar", ayetCount: 182, type: "Mekki" },
  { no: 38, turkish: "Sâd", arabic: "صٓ", english: "Sad", meaning: "Sâd", ayetCount: 88, type: "Mekki" },
  { no: 39, turkish: "Zümer", arabic: "ٱلزُّمَر", english: "Az-Zumar", meaning: "Topluluklar", ayetCount: 75, type: "Mekki" },
  { no: 40, turkish: "Mü'min", arabic: "غَافِر", english: "Ghafir", meaning: "Bağışlayan", ayetCount: 85, type: "Mekki" },
  { no: 41, turkish: "Fussilet", arabic: "فُصِّلَت", english: "Fussilat", meaning: "Açıklanmış", ayetCount: 54, type: "Mekki" },
  { no: 42, turkish: "Şûrâ", arabic: "ٱلشُّورَىٰ", english: "Ash-Shura", meaning: "Danışma", ayetCount: 53, type: "Mekki" },
  { no: 43, turkish: "Zuhruf", arabic: "ٱلزُّخْرُف", english: "Az-Zukhruf", meaning: "Süs", ayetCount: 89, type: "Mekki" },
  { no: 44, turkish: "Duhân", arabic: "ٱلدُّخَان", english: "Ad-Dukhan", meaning: "Duman", ayetCount: 59, type: "Mekki" },
  { no: 45, turkish: "Câsiye", arabic: "ٱلْجَاثِيَة", english: "Al-Jathiyah", meaning: "Diz Çökmüş", ayetCount: 37, type: "Mekki" },
  { no: 46, turkish: "Ahkâf", arabic: "ٱلْأَحْقَاف", english: "Al-Ahqaf", meaning: "Kum Tepeleri", ayetCount: 35, type: "Mekki" },
  { no: 47, turkish: "Muhammed", arabic: "مُحَمَّد", english: "Muhammad", meaning: "Muhammed", ayetCount: 38, type: "Medeni" },
  { no: 48, turkish: "Fetih", arabic: "ٱلْفَتْح", english: "Al-Fath", meaning: "Fetih", ayetCount: 29, type: "Medeni" },
  { no: 49, turkish: "Hucurât", arabic: "ٱلْحُجُرَات", english: "Al-Hujurat", meaning: "Odalar", ayetCount: 18, type: "Medeni" },
  { no: 50, turkish: "Kâf", arabic: "قٓ", english: "Qaf", meaning: "Kâf", ayetCount: 45, type: "Mekki" },
  { no: 51, turkish: "Zâriyât", arabic: "ٱلذَّارِيَات", english: "Adh-Dhariyat", meaning: "Tozutucular", ayetCount: 60, type: "Mekki" },
  { no: 52, turkish: "Tûr", arabic: "ٱلطُّور", english: "At-Tur", meaning: "Tûr Dağı", ayetCount: 49, type: "Mekki" },
  { no: 53, turkish: "Necm", arabic: "ٱلنَّجْم", english: "An-Najm", meaning: "Yıldız", ayetCount: 62, type: "Mekki" },
  { no: 54, turkish: "Kamer", arabic: "ٱلْقَمَر", english: "Al-Qamar", meaning: "Ay", ayetCount: 55, type: "Mekki" },
  { no: 55, turkish: "Rahmân", arabic: "ٱلرَّحْمَٰن", english: "Ar-Rahman", meaning: "Çok Merhametli", ayetCount: 78, type: "Medeni" },
  { no: 56, turkish: "Vâkıa", arabic: "ٱلْوَاقِعَة", english: "Al-Waqi'ah", meaning: "Olay", ayetCount: 96, type: "Mekki" },
  { no: 57, turkish: "Hadîd", arabic: "ٱلْحَدِيد", english: "Al-Hadid", meaning: "Demir", ayetCount: 29, type: "Medeni" },
  { no: 58, turkish: "Mücâdele", arabic: "ٱلْمُجَادَلَة", english: "Al-Mujadilah", meaning: "Mücadele Eden", ayetCount: 22, type: "Medeni" },
  { no: 59, turkish: "Haşr", arabic: "ٱلْحَشْر", english: "Al-Hashr", meaning: "Sürgün", ayetCount: 24, type: "Medeni" },
  { no: 60, turkish: "Mümtehine", arabic: "ٱلْمُمْتَحِنَة", english: "Al-Mumtahanah", meaning: "İmtihan Edilen", ayetCount: 13, type: "Medeni" },
  { no: 61, turkish: "Saff", arabic: "ٱلصَّفّ", english: "As-Saf", meaning: "Saf", ayetCount: 14, type: "Medeni" },
  { no: 62, turkish: "Cum'a", arabic: "ٱلْجُمُعَة", english: "Al-Jumu'ah", meaning: "Cuma", ayetCount: 11, type: "Medeni" },
  { no: 63, turkish: "Münâfikûn", arabic: "ٱلْمُنَافِقُون", english: "Al-Munafiqun", meaning: "Münafıklar", ayetCount: 11, type: "Medeni" },
  { no: 64, turkish: "Tegâbün", arabic: "ٱلتَّغَابُن", english: "At-Taghabun", meaning: "Aldanma", ayetCount: 18, type: "Medeni" },
  { no: 65, turkish: "Talâk", arabic: "ٱلطَّلَاق", english: "At-Talaq", meaning: "Boşanma", ayetCount: 12, type: "Medeni" },
  { no: 66, turkish: "Tahrîm", arabic: "ٱلتَّحْرِيم", english: "At-Tahrim", meaning: "Yasaklamak", ayetCount: 12, type: "Medeni" },
  { no: 67, turkish: "Mülk", arabic: "ٱلْمُلْك", english: "Al-Mulk", meaning: "Hükümranlık", ayetCount: 30, type: "Mekki" },
  { no: 68, turkish: "Kalem", arabic: "ٱلْقَلَم", english: "Al-Qalam", meaning: "Kalem", ayetCount: 52, type: "Mekki" },
  { no: 69, turkish: "Hâkka", arabic: "ٱلْحَاقَّة", english: "Al-Haqqah", meaning: "Gerçek Olan", ayetCount: 52, type: "Mekki" },
  { no: 70, turkish: "Meâric", arabic: "ٱلْمَعَارِج", english: "Al-Ma'arij", meaning: "Yükseliş Yolları", ayetCount: 44, type: "Mekki" },
  { no: 71, turkish: "Nûh", arabic: "نُوح", english: "Nuh", meaning: "Nuh", ayetCount: 28, type: "Mekki" },
  { no: 72, turkish: "Cinn", arabic: "ٱلْجِنّ", english: "Al-Jinn", meaning: "Cinler", ayetCount: 28, type: "Mekki" },
  { no: 73, turkish: "Müzzemmil", arabic: "ٱلْمُزَّمِّل", english: "Al-Muzzammil", meaning: "Örtünmüş", ayetCount: 20, type: "Mekki" },
  { no: 74, turkish: "Müddessir", arabic: "ٱلْمُدَّثِّر", english: "Al-Muddaththir", meaning: "Bürünmüş", ayetCount: 56, type: "Mekki" },
  { no: 75, turkish: "Kıyâme", arabic: "ٱلْقِيَامَة", english: "Al-Qiyamah", meaning: "Kıyamet", ayetCount: 40, type: "Mekki" },
  { no: 76, turkish: "İnsân", arabic: "ٱلْإِنْسَان", english: "Al-Insan", meaning: "İnsan", ayetCount: 31, type: "Medeni" },
  { no: 77, turkish: "Mürselât", arabic: "ٱلْمُرْسَلَات", english: "Al-Mursalat", meaning: "Gönderilenler", ayetCount: 50, type: "Mekki" },
  { no: 78, turkish: "Nebe'", arabic: "ٱلنَّبَإ", english: "An-Naba", meaning: "Haber", ayetCount: 40, type: "Mekki" },
  { no: 79, turkish: "Nâziât", arabic: "ٱلنَّازِعَات", english: "An-Nazi'at", meaning: "Söküp Çıkaranlar", ayetCount: 46, type: "Mekki" },
  { no: 80, turkish: "Abese", arabic: "عَبَسَ", english: "Abasa", meaning: "Yüzünü Ekşitti", ayetCount: 42, type: "Mekki" },
  { no: 81, turkish: "Tekvîr", arabic: "ٱلتَّكْوِير", english: "At-Takwir", meaning: "Dürülme", ayetCount: 29, type: "Mekki" },
  { no: 82, turkish: "İnfitâr", arabic: "ٱلْإِنْفِطَار", english: "Al-Infitar", meaning: "Yarılma", ayetCount: 19, type: "Mekki" },
  { no: 83, turkish: "Mutaffifîn", arabic: "ٱلْمُطَفِّفِين", english: "Al-Mutaffifin", meaning: "Ölçüde Hile Yapanlar", ayetCount: 36, type: "Mekki" },
  { no: 84, turkish: "İnşikâk", arabic: "ٱلْإِنْشِقَاق", english: "Al-Inshiqaq", meaning: "Yarılma", ayetCount: 25, type: "Mekki" },
  { no: 85, turkish: "Bürûc", arabic: "ٱلْبُرُوج", english: "Al-Buruj", meaning: "Burçlar", ayetCount: 22, type: "Mekki" },
  { no: 86, turkish: "Târık", arabic: "ٱلطَّارِق", english: "At-Tariq", meaning: "Geceleyin Gelen", ayetCount: 17, type: "Mekki" },
  { no: 87, turkish: "A'lâ", arabic: "ٱلْأَعْلَىٰ", english: "Al-A'la", meaning: "En Yüce", ayetCount: 19, type: "Mekki" },
  { no: 88, turkish: "Gâşiye", arabic: "ٱلْغَاشِيَة", english: "Al-Ghashiyah", meaning: "Kaplayan", ayetCount: 26, type: "Mekki" },
  { no: 89, turkish: "Fecr", arabic: "ٱلْفَجْر", english: "Al-Fajr", meaning: "Şafak", ayetCount: 30, type: "Mekki" },
  { no: 90, turkish: "Beled", arabic: "ٱلْبَلَد", english: "Al-Balad", meaning: "Şehir", ayetCount: 20, type: "Mekki" },
  { no: 91, turkish: "Şems", arabic: "ٱلشَّمْس", english: "Ash-Shams", meaning: "Güneş", ayetCount: 15, type: "Mekki" },
  { no: 92, turkish: "Leyl", arabic: "ٱللَّيْل", english: "Al-Layl", meaning: "Gece", ayetCount: 21, type: "Mekki" },
  { no: 93, turkish: "Duhâ", arabic: "ٱلضُّحَىٰ", english: "Ad-Duha", meaning: "Kuşluk", ayetCount: 11, type: "Mekki" },
  { no: 94, turkish: "İnşirâh", arabic: "ٱلشَّرْح", english: "Ash-Sharh", meaning: "Genişletme", ayetCount: 8, type: "Mekki" },
  { no: 95, turkish: "Tîn", arabic: "ٱلتِّين", english: "At-Tin", meaning: "İncir", ayetCount: 8, type: "Mekki" },
  { no: 96, turkish: "Alâk", arabic: "ٱلْعَلَق", english: "Al-Alaq", meaning: "Asılı", ayetCount: 19, type: "Mekki" },
  { no: 97, turkish: "Kadr", arabic: "ٱلْقَدْر", english: "Al-Qadr", meaning: "Kadir Gecesi", ayetCount: 5, type: "Mekki" },
  { no: 98, turkish: "Beyyine", arabic: "ٱلْبَيِّنَة", english: "Al-Bayyinah", meaning: "Açık Delil", ayetCount: 8, type: "Medeni" },
  { no: 99, turkish: "Zilzâl", arabic: "ٱلزَّلْزَلَة", english: "Az-Zalzalah", meaning: "Sarsıntı", ayetCount: 8, type: "Medeni" },
  { no: 100, turkish: "Âdiyât", arabic: "ٱلْعَادِيَات", english: "Al-Adiyat", meaning: "Saldıran Atlar", ayetCount: 11, type: "Mekki" },
  { no: 101, turkish: "Kâria", arabic: "ٱلْقَارِعَة", english: "Al-Qari'ah", meaning: "Kapı Çalan", ayetCount: 11, type: "Mekki" },
  { no: 102, turkish: "Tekâsür", arabic: "ٱلتَّكَاثُر", english: "At-Takathur", meaning: "Çoğalma Yarışı", ayetCount: 8, type: "Mekki" },
  { no: 103, turkish: "Asr", arabic: "ٱلْعَصْر", english: "Al-Asr", meaning: "İkindi", ayetCount: 3, type: "Mekki" },
  { no: 104, turkish: "Hümeze", arabic: "ٱلْهُمَزَة", english: "Al-Humazah", meaning: "Arkadan Çekiştiren", ayetCount: 9, type: "Mekki" },
  { no: 105, turkish: "Fîl", arabic: "ٱلْفِيل", english: "Al-Fil", meaning: "Fil", ayetCount: 5, type: "Mekki" },
  { no: 106, turkish: "Kureyş", arabic: "قُرَيْش", english: "Quraysh", meaning: "Kureyş", ayetCount: 4, type: "Mekki" },
  { no: 107, turkish: "Mâûn", arabic: "ٱلْمَاعُون", english: "Al-Ma'un", meaning: "Yardımlaşma", ayetCount: 7, type: "Mekki" },
  { no: 108, turkish: "Kevser", arabic: "ٱلْكَوْثَر", english: "Al-Kawthar", meaning: "Bolluk", ayetCount: 3, type: "Mekki" },
  { no: 109, turkish: "Kâfirûn", arabic: "ٱلْكَافِرُون", english: "Al-Kafirun", meaning: "İnkâr Edenler", ayetCount: 6, type: "Mekki" },
  { no: 110, turkish: "Nasr", arabic: "ٱلنَّصْر", english: "An-Nasr", meaning: "Yardım", ayetCount: 3, type: "Medeni" },
  { no: 111, turkish: "Tebbet", arabic: "ٱلْمَسَد", english: "Al-Masad", meaning: "Bükülmüş Lif", ayetCount: 5, type: "Mekki" },
  { no: 112, turkish: "İhlâs", arabic: "ٱلْإِخْلَاص", english: "Al-Ikhlas", meaning: "Samimiyet", ayetCount: 4, type: "Mekki" },
  { no: 113, turkish: "Felâk", arabic: "ٱلْفَلَق", english: "Al-Falaq", meaning: "Tan Yeri", ayetCount: 5, type: "Mekki" },
  { no: 114, turkish: "Nâs", arabic: "ٱلنَّاس", english: "An-Nas", meaning: "İnsanlar", ayetCount: 6, type: "Mekki" },
];

export function getSurahMeta(no: number): SurahMeta | undefined {
  return SURELER_META.find((s) => s.no === no);
}

export function getSurahAudioUrl(no: number): string {
  return `https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/${no}.mp3`;
}
